spring:
  datasource:
    url: ${PROD_DB_URL:jdbc:postgresql://localhost:5432/cloud_storage}
    username: ${PROD_DB_USERNAME:cloud}
    password: ${PROD_DB_PASSWORD:cloud}
    driver-class-name: org.postgresql.Driver
